### PR TITLE
`trailingSlash` Configuration Option (Closes #27)

### LINKED ISSUE #27: Trailing Slash
When forcing a trailing slash during dev (using `trailingSlash: 'always'` in `astro.config.js` you'll want to include trailing slashes in the URLs generated by the `l()` function. Right now astro-i18n will always remove the trailing slash:

https://github.com/Alexandre-Fernandez/astro-i18n/blob/2eaca61b939bd22cc6ddb33459f38e760a2d0b26/lib/filesystem/index.ts#L90-L93

I'd like to either have a separate config option in astro-i18n like `trailingSlash: 'always' | 'never'` and/or read from the Astro config's `trailingSlash` option (although I'm not sure how `ignore` would be handled if matching the Astro config).

More than happy to work on a PR if you agree with this (and thanks for an amazing project)!

### PR DESCRIPTION
**Pull request by lorenzolewis**
Creating this as a draft at first. I'm admittedly not good with using local node packages so I haven't been able to fully test this. If you have any suggestions on workflow then I should be able to get the rest of the below list knocked out easily. 

- [x] Add a `trailingSlash` option to the config with options of `always` and `never`, defaults to `never`
- [x] Automatically detect from Astro Config's `trailingSlash` option
- [x] Documentation: Will be more than happy to add in after I've had a chance to test.
- [ ] Tests? Would you like any sort of tests added to this?

Closes #27

### CODE REVIEW

**Comment by lorenzolewis** [comment]
Was able to get this tested locally (thanks @FabianLars)!

Now it will use the value from Astro's config if not defined in the i18n config (only if `never` or `always`) and will also log a warning to the console if they conflict. It will default to `never` if not specified anywhere as you mentioned in #27.

One issue I'm having is that the state that `routing` reads from doesn't seem to use the value from the configs during `astro dev`. I put in a `console.log` here to show that:

https://github.com/Alexandre-Fernandez/astro-i18n/blob/12729e00a8bd3f49e4a98498fc3337b7c733d88e/src/core/routing/index.ts#L56-L58

**Comment by lorenzolewis** [comment]
This is ready to go!

The only thing to note is that a `trailingSlash` value of `always` or `never` in Astro's config **will be prioritised** over a set value in astro-i18n's config. This might want to be switched the other way around but it seems that the state management that `routes` depends on a value of `undefined` for choosing to set properties or not. Not exactly sure how that could be overcome without some changes I wasn't comfortable making without knowing the imapcts.

Happy for any feedback!

**Comment by Alexandre-Fernandez** [comment]
I tested your main branch and it doesn't seem to work, whatever I do with the trailingSlash property, be it on our config or on the astro one doesn't change any behaviour for the `l` function.

**Comment by lorenzolewis** [comment]
Just out of curiosity, if you inspect the HTML and an `a` element could you see if that has it? I noticed some browsers won't show it in the status bar like in your screenshot.

**Comment by Alexandre-Fernandez** [comment]
image
Here's a screen of the `<a>`, I'll try to take a look into this.
How did you get it to work locally ?

**Comment by lorenzolewis** [comment]
@Alexandre-Fernandez turns out I overlooked the separate return in the route function for if a locale is rendered in the route (and I only tested with `showDefaultLangCode: false`).

A fix should be pushed for that now 🎉

**Comment by Alexandre-Fernandez** [comment]
Thanks for this fix.
I tested with `showDefaultLangCode: false` and it worked.
However it looked like the `astro.config.mjs`'s `trailingSlash` property was taking priority over the `astro.i18n.config.ts` one, can you make it have the reverse behaviour ?

**Comment by lorenzolewis** [comment]
Apologies for the delay, it will be a little bit before I can dig into this. 

In the current lifecycle it seems that the default i18n config gets applied before the hook that would allow me to read from Astro's config gets run. I originally tried to have the default be undefined but an undefined value doesn't seem to get applied from the state store with the way values are read in.

**Comment by Alexandre-Fernandez** [comment]
Didn't think much about it but a quick and easy way would be to add the `"ignore"` value as default, which would have the same behaviour as `"never"` but mean that the user didn't override it. 
Otherwise you'd probably need to modify the default value logic.

**Comment by lorenzolewis** [comment]
I ended up just rolling this back to not pull from the main Astro config. The `ignore` option made sense but I felt like it was confusing unless you really sat down to think through it. I pushed some changes with an initial implementation for that but haven't been able to fully test it yet (will try to do that next week).

**Comment by Alexandre-Fernandez** [comment]
Thanks it looks great, I'll try to check it as soon as I can to merge it.

**Comment by brunoprietog** [comment]
@Alexandre-Fernandez Don't you think that trailing slash should be default in always? This is Astro's default value, and I had a hard time figuring out why there was no match between the links generated with l and the links returned by Astro.

**Pull request merged**
